### ISSUE TITLE
Ошибка при подключении клиента

### ISSUE THREAD

**Issue by TooLazyToCreate** [Assasans/TXServer-Public#3]
Честно, в душе не чаю, от чего мог произойти сей инцидент:
```
[10.01.2022 18:14:41, INFO] 127.0.0.1:60303 has connected.
[10.01.2022 18:14:41, TRACE] Sent to 127.0.0.1:60303 (1641838481927): {
        InitTimeCommand [ServerTime: 1641838481926]
}
[10.01.2022 18:14:41, DEBUG] 127.0.0.1:60303 (1641838481927): Invalid packet magic: 47-45
[10.01.2022 18:14:41, INFO] 127.0.0.1:60303 (1641838481927) has disconnected.
[10.01.2022 18:14:41, ERROR] 127.0.0.1:60303 (1641838481927): System.IO.IOException: The operation is not allowed on non-connected sockets.
   at System.Net.Sockets.NetworkStream..ctor(Socket socket, FileAccess access, Boolean ownsSocket)
   at System.Net.Sockets.NetworkStream..ctor(Socket socket)
   at TXServer.Core.PlayerConnection.SendCommands(ICommand[] commands) in C:\Users\root\Desktop\TXServer-Public-master\TXServer\Core\Player\PlayerConnection.cs:line 206
   at TXServer.Core.PlayerConnection.ServerSideEvents() in C:\Users\root\Desktop\TXServer-Public-master\TXServer\Core\Player\PlayerConnection.cs:line 92
```

**Comment by Donatik3310** [comment]
а как запустить сервер?

**Comment by Donatik3310** [comment]
а у тебя он вообще подключался к серверу?
